version: '3.8'
services:
  datalakehouse:
    build: ./datalakehouse
    # Add configs/ports as needed

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - python-api
      - java-api

  python-api:
    build: ./python-api
    ports:
      - "5000:5000"
    depends_on:
      - sql-db

  java-api:
    build: ./java-api
    ports:
      - "8080:8080"
    depends_on:
      - sql-db

# docker-compose.yaml (snippet)
  sql-db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: home_loan
    ports:
      - "5432:5432"
    volumes:
      - sql-db-data:/var/lib/postgresql/data
      - ./sql-db/init:/docker-entrypoint-initdb.d

volumes:
  sql-db-data: